export const MASSAGES_ONLINE = [
	{
		name: "user1",
		img: "/assets/image/online_image1.svg",
		img_alt: "user1",
		online: true,
	},
	{
		name: "user2",
		img: "/assets/image/online_image2.svg",
		img_alt: "user1",
		online: true,
	},
	{
		name: "user3",
		img: "/assets/image/online_image4.svg",
		img_alt: "user3",
		online: true,
	},
	{
		name: "user3",
		img: "/assets/image/online_image4.svg",
		img_alt: "user3",
		online: true,
	},
	{
		name: "user3",
		img: "/assets/image/online_image4.svg",
		img_alt: "user3",
		online: true,
	},
	{
		name: "user3",
		img: "/assets/image/online_image4.svg",
		img_alt: "user3",
		online: true,
	},
	{
		name: "user4",
		img: "/assets/image/online_image4.svg",
		img_alt: "user4",
		online: true,
	},
	{
		name: "user1",
		img: "/assets/image/online_image1.svg",
		img_alt: "user1",
		online: false,
	},
	{
		name: "user5",
		img: "/assets/image/online_image4.svg",
		img_alt: "user5",
		online: true,
	},
	{
		name: "user1",
		img: "/assets/image/online_image1.svg",
		img_alt: "user1",
		online: true,
	},
	{
		name: "user2",
		img: "/assets/image/online_image2.svg",
		img_alt: "user1",
		online: true,
	},
	{
		name: "user3",
		img: "/assets/image/online_image4.svg",
		img_alt: "user3",
		online: true,
	},
	{
		name: "user4",
		img: "/assets/image/online_image4.svg",
		img_alt: "user4",
		online: true,
	},
	{
		name: "user5",
		img: "/assets/image/online_image4.svg",
		img_alt: "user5",
		online: true,
	},
	{
		name: "user6",
		img: "/assets/image/online_image6.svg",
		img_alt: "user6",
		online: true,
	},
	{
		name: "Anne Snow",
		img: "/assets/image/message_img1.svg",
		img_alt: "Anne Snow",
		messages: ["did you get it?", "Hello!"],
		online: true,
		read: false,
	},
	{
		name: "Sara Williams",
		img: "/assets/image/message_img2.svg",
		img_alt: "Sara Williams",
		messages: ["Hello!", "Hi", "okay", "Thank you for the support"],
		online: false,
		read: false,
	},
	{
		name: "John Smith",
		img: "/assets/image/message_img3.svg",
		img_alt: "John Smith",
		messages: ["Hello!", "No worries"],
		online: false,
		read: true,
	},
	{
		name: "John Snow",
		img: "/assets/image/message_img4.svg",
		img_alt: "John Snow",
		messages: ["Hello!", "Hello!"],
		online: true,
		read: true,
	},
	{
		name: "Sara Williams",
		img: "/assets/image/message_img5.svg",
		img_alt: "Sara Williams",
		messages: ["Hello!", "Hi", "okay", "Thank you for the support"],
		online: false,
		read: true,
	},
	{
		name: "John Smith",
		img: "/assets/image/message_img6.svg",
		img_alt: "John Smith",
		messages: ["Hello!", "No worries"],
		online: true,
		read: true,
	},
	{
		name: "John Snow",
		img: "/assets/image/message_img7.svg",
		img_alt: "John Snow",
		messages: ["Hello!", "No worries"],
		online: false,
		read: true,
	},
	{
		name: "John Snow",
		img: "/assets/image/message_img7.svg",
		img_alt: "John Snow",
		messages: ["Hello!", "No worries"],
		online: false,
		read: true,
	},
	{
		name: "John Snow",
		img: "/assets/image/message_img7.svg",
		img_alt: "John Snow",
		messages: ["Hello!", "No worries"],
		online: false,
		read: true,
	},
	{
		name: "John Snow",
		img: "/assets/image/message_img7.svg",
		img_alt: "John Snow",
		messages: ["Hello!", "No worries"],
		online: false,
		read: true,
	},
	{
		name: "John Snow",
		img: "/assets/image/message_img7.svg",
		img_alt: "John Snow",
		messages: ["Hello!", "No worries"],
		online: false,
		read: true,
	},
];
